### ISSUE TITLE
UnityWeb Compressed Content (brotli)

### ISSUE THREAD

**Issue by hendev1** [akio7624/uwdtool#1]
Will you support the UnityWeb Compressed Content (brotli) file signature in the future? I cant read that type of files.

**Comment by yuria0309** [comment]
Do you mean the Unity WebData binary file compressed into brotli? Do you have any sample files?

**Comment by hendev1** [comment]
The binary file signature is: 
![image](https://github.com/yuria0309/uwdtool/assets/141557024/a659ce45-8aa5-42e1-bcd0-46aa7b489eaa)

**Comment by yuria0309** [comment]
ok, I knew how that was created.

When you build a WebGL project in Unity, the data file and wasm are compressed into brotli when you set the Brotli compression option.
Since the brotli does not have a magic byte, Unity inserts a specific string into the compressed file to distinguish the type of file.
That string is "UnityWeb Compressed Content (brotli)".
Comments have been added, but you can still decompress directly with the brotli tool.

I think i can implement the part that detects the comment in uwdt.(also gzip)
The logic to detect this comment can be seen in UnityLoader.js.

```js
hasUnityMarker: function (data) {
    var expectedComment = "UnityWeb Compressed Content (brotli)";
    if (!data.length)
      return false;
    var WBITS_length = (data[0] & 0x01) ? (data[0] & 0x0E) ? 4 : 7 : 1,
        WBITS = data[0] & ((1 << WBITS_length) - 1),
        MSKIPBYTES = 1 + ((Math.log(expectedComment.length - 1) / Math.log(2)) >> 3);
        commentOffset = (WBITS_length + 1 + 2 + 1 + 2 + (MSKIPBYTES << 3) + 7) >> 3;
    if (WBITS == 0x11 || commentOffset > data.length)
      return false;
    var expectedCommentPrefix = WBITS + (((3 << 1) + (MSKIPBYTES << 4) + ((expectedComment.length - 1) << 6)) << WBITS_length);
    for (var i = 0; i < commentOffset; i++, expectedCommentPrefix >>>= 8) {
      if (data[i] != (expectedCommentPrefix & 0xFF))
        return false;
    }
    return String.fromCharCode.apply(null, data.subarray(commentOffset, commentOffset + expectedComment.length)) == expectedComment;
    
}
```

I'm going to move this code to Python and implement that function.

**Comment by yuria0309** [comment]
Additionally, it seems that this method was used in Unity 2019. I don't know when, but lately Unity seems to distinguish compression types by file extensions.

**Comment by yuria0309** [comment]
uwdt was created for the purpose of reading already decompressed UnityWebData files.
So I think I need to think about how to add this feature.
You can use it with uwdt after changing the file's extension to .br and decompressing it with software such as PeaZip or BandiZip.

**Comment by hendev1** [comment]
I found a project (https://github.com/SeriousCache/UABE/issues/312#issuecomment-1774005194) that can decompress brotli files. Thats for your work and time. Sorry for disturbing you.

**Comment by yuria0309** [comment]
That's fine, and I think this feature is worth exploring.

**Comment by akio7624** [comment]
Sorry for the delay. Support for compressed *.unityweb files used up to Unity 2019 has been added in version 1.3.0
